name: C++ Test

run-name: C++ tests

on:
  push:
      branches:
      - main
  pull_request:
      branches:    
      - main
  workflow_dispatch:

jobs:
  cpp-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install requirements on MacOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install cmake googletest eigen libomp lcov

      - name: Install requirements on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install cmake libgtest-dev libeigen3-dev lcov

      - name: Compile on MacOS
        if: matrix.os == 'macos-latest'
        run: |
          g++ -Og -std=c++17 --coverage tests/cpp_tests/test_main.cpp -Xclang -fopenmp -lgtest -lomp -o tests/cpp_tests/cpp_test -I $(brew --prefix eigen)/include/eigen3/ -I $(brew --prefix libomp)/include -L $(brew --prefix libomp)/lib

      - name: Compile on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          g++ -Og -std=c++17 --coverage tests/cpp_tests/test_main.cpp -fopenmp -lgtest -o tests/cpp_tests/cpp_test -I /usr/include/eigen3/

      - name: Test
        run: |
          ./tests/cpp_tests/cpp_test

      - name: Generate Coverage Report on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          lcov --directory . --capture --output-file coverage.info # カバレッジデータを収集
          lcov --remove coverage.info '/usr/*' '**/gtest/**' '**/test_main.cpp' --output-file coverage.info # 余分なデータを除外
          lcov --list coverage.info # カバレッジレポートの内容を表示（オプショナル）

      # MacOSでのカバレッジデータの収集とフォーマット
      - name: Generate Coverage Report on MacOS
        if: matrix.os == 'macos-latest'
        run: |
          lcov --directory . --capture --output-file coverage.info # カバレッジデータを収集
          lcov --remove coverage.info '/usr/*' '**/gtest/**' '**/test_main.cpp' --output-file coverage.info # 余分なデータを除外
          lcov --list coverage.info # カバレッジレポートの内容を表示（オプショナル）

      # Codecovにカバレッジデータをアップロード
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.info
          fail_ci_if_error: true