name: Build API reference

run-name: Build API reference

on: 
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install doxygen
        run: sudo apt install doxygen

      - name: Build docs
        run: doxygen
