name: Publish Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel twine

      - name: Install libomp on MacOS
        if: matrix.os == 'macos-14'
        run: |
          brew install libomp

      - name: Build and publish for Linux
        if: matrix.os == 'ubuntu-latest'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          CIBW_BUILD: cp39-manylinux_x86_64 cp310-manylinux_x86_64 cp311-manylinux_x86_64 cp312-manylinux_x86_64 
          CIBW_BUILD_VERBOSITY: 3
        run: |
          cibuildwheel --output-dir wheelhouse
          twine upload wheelhouse/* --repository pypi

      - name: Build and publish for MacOS (Intel)
        if: matrix.os == 'macos-latest'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          CIBW_BUILD: cp39-macosx_x86_64 cp310-macosx_x86_64 cp311-macosx_x86_64 cp312-macosx_x86_64
          CIBW_BUILD_VERBOSITY: 3
        run: |
          cibuildwheel --output-dir wheelhouse
          twine upload wheelhouse/* --repository pypi

      - name: Build and publish for MacOS (M1)
        if: matrix.os == 'macos-14'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          CIBW_BUILD: cp310-macosx_arm64 cp311-macosx_arm64 cp312-macosx_arm64
          CIBW_BUILD_VERBOSITY: 3
        run: |
          cibuildwheel --output-dir wheelhouse
          twine upload wheelhouse/* --repository pypi
