name: Python Test

run-name: Python tests triggered by Pull Request @${{ github.actor }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main
  workflow_dispatch:

jobs:
  python-test-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is test"