name: Python Test

run-name: Python tests triggered by Pull Request @${{ github.actor }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main
  workflow_dispatch:

jobs:
  python-test-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Install dependencies Eigen
        run: |
          sudo apt-get install libeigen3-dev

      - name: Install ${{ github.event.repository.name }}
        run: |
          python -m pip install . -vvv