name: Python Test

run-name: Python tests triggered by @${{ github.actor }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main
  workflow_dispatch:

jobs:
  python-test:
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Install dependencies Eigen on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install libeigen3-dev

      - name: Install dependencies Eigen on MacOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install eigen

      - name: Install ${{ github.event.repository.name }}
        run: |
          python -m pip install . -vvv

      - name: Run tests
        run: |
          python -m pytest -v tests